export const users: any[] = [
  {
    name: "Admin",
    email: "admin@admin.com",
    password: "admin123",
    role: "admin",
  },
  {
    name: "Seller",
    email: "seller@seller.com",
    password: "seller123",
    role: "seller",
  },
  {
    name: "Buyer",
    email: "buyer@buyer.com",
    password: "buyer123",
    role: "buyer",
  },
];

export const products: any[] = [
  {
    name: "Terracotta Plant Pot",
    category: "Home Decor",
    price: 15,
    stock: 10,
    rating: 4.5,
    rating_count: 200,
    image: "https:\/\/i.ibb.co\/gMsLBjDv\/terracota-plant-pot.webp",
    description: "A rustic terracotta pot for indoor and outdoor plants.",
    details: "This terracotta pot is durable and breathable, ideal for healthy plant growth and rustic charm.",
  },
  {
    name: "Knitted Blanket",
    category: "Home Decor",
    price: 45,
    stock: 10,
    rating: 4.8,
    rating_count: 150,
    image: "https:\/\/i.ibb.co\/Z1KQP1Jm\/knitted-blanket.webp",
    description: "A cozy knitted blanket to keep you warm and stylish.",
    details: "This knitted blanket is soft, warm, and perfect for both comfort and home décor.",
  },
  {
    name: "Glass Vase",
    category: "Home Decor",
    price: 28,
    stock: 10,
    rating: 4.3,
    rating_count: 70,
    image: "https:\/\/i.ibb.co\/chdCpwDD\/glass-vase.webp",
    description: "A minimalist glass vase ideal for flowers or decorative arrangements.",
    details: "This clear glass vase adds elegance to any room, suitable for fresh or dried flowers.",
  },
  {
    name: "Wooden Bowl",
    category: "Home Decor",
    price: 25,
    stock: 10,
    rating: 4.5,
    rating_count: 120,
    image: "https:\/\/i.ibb.co\/HDZHqx19\/wooden-bowl.webp",
    description: "A handcrafted wooden bowl perfect for home décor or serving.",
    details: "This wooden bowl is made from quality natural wood and finished for a smooth, elegant look.",
  },
  {
    name: "Leather Journal",
    category: "Home Decor",
    price: 22,
    stock: 10,
    rating: 4.6,
    rating_count: 95,
    image: "https:\/\/i.ibb.co\/x8C3PrQV\/leather-journal.webp",
    description: "A handcrafted leather-bound journal for writing and sketching.",
    details: "This leather journal is perfect for capturing thoughts, sketches, and ideas with timeless style.",
  },
  {
    name: "Ceramic Mug",
    category: "Home Decor",
    price: 18,
    stock: 10,
    rating: 4.2,
    rating_count: 85,
    image: "https:\/\/i.ibb.co\/MDRSmDmr\/ceramic-mug.webp",
    description: "A beautifully made ceramic mug for your favorite hot drink.",
    details: "This ceramic mug is handcrafted with care, perfect for enjoying your favorite beverages.",
  },
  {
    name: "Handwoven Basket",
    category: "Home Decor",
    price: 30,
    stock: 10,
    rating: 4.7,
    rating_count: 60,
    image: "https:\/\/i.ibb.co\/GfJVdQv3\/handwoven-basket.webp",
    description: "A natural woven basket great for storage and decoration.",
    details: "This handwoven basket is made from natural materials, ideal for both storage and decorative purposes.",
  },
  {
    name: "Rustic Wall Sign",
    category: "Home Decor",
    price: 28,
    stock: 10,
    rating: 4.9,
    image: "/images/homedecor1.png",
    description: "A handcrafted rustic wooden wall sign perfect for cozy spaces.",
    details: "This rustic wall sign is made from high-quality wood and adds a charming touch to any room.",
  },
  {
    name: "Decor Shelf",
    category: "Home Decor",
    price: 32,
    stock: 3,
    rating: 4.8,
    image: "/images/homedecor2.png",
    description: "Minimalist wooden shelf ideal for modern home styling.",
    details: "This decor shelf is crafted from premium wood, perfect for displaying your favorite items.",
  },
  {
    name: "Cozy Decor Set",
    category: "Home Decor",
    price: 35,
    rating: 4.7,
    image: "/images/homedecor3.png",
    description: "A complete cozy decor set to elevate your living space.",
    details: "This cozy decor set includes carefully selected items to enhance the comfort and style of your home.",
  },
  {
    name: "Ceramic Plate",
    category: "Kitchen",
    price: 20,
    stock: 10,
    rating: 4.7,
    image: "/images/kitchen1.png",
    description: "Handmade ceramic plate crafted with attention to detail.",
    details: "This ceramic plate is perfect for serving food or as a decorative piece in your kitchen.",
  },
  {
    name: "Handmade Mug",
    category: "Kitchen",
    price: 18,
    stock: 10,
    rating: 4.8,
    image: "/images/kitchen2.png",
    description: "A cozy handmade mug perfect for your morning coffee.",
    details: "This handmade mug is ideal for enjoying your favorite hot beverages with style and comfort.",
  },
  {
    name: "Wooden Bowl",
    category: "Kitchen",
    price: 22,
    stock: 10,
    rating: 4.9,
    image: "/images/kitchen3.png",
    description: "Natural wooden bowl with a smooth handcrafted finish.",
    details: "This wooden bowl is perfect for serving food or as a decorative piece in your kitchen.",
  },
  {
    name: "Glass Cup Set",
    category: "Kitchen",
    price: 25,
    stock: 10,
    rating: 4.6,
    image: "/images/glass1.png",
    description: "Elegant glass cup set for everyday or special occasions.",
    details: "This glass cup set is perfect for serving beverages in style, whether for daily use or special occasions.",
  },
  {
    name: "Beaded Bracelet",
    category: "Jewelry",
    price: 12,
    stock: 10,
    rating: 4.8,
    image: "/images/jewelry4.png",
    description: "Colorful handmade bracelet designed with care.",
    details: "This beaded bracelet is handcrafted with attention to detail, making it a unique accessory for any outfit.",
  },
  {
    name: "Handmade Ring",
    category: "Jewelry",
    price: 15,
    stock: 10,
    rating: 4.7,
    image: "/images/jewelry2.png",
    description: "A unique handcrafted ring to match your style.",
    details: "This handmade ring is crafted with precision, offering a distinctive touch to your jewelry collection.",
  },
  {
    name: "Clay Earrings",
    category: "Jewelry",
    price: 14,
    stock: 10,
    rating: 4.9,
    image: "/images/jewelry3.png",
    description: "Lightweight clay earrings with modern designs.",
    details: "These clay earrings are designed for comfort and style, perfect for any occasion.",
  },
  {
    name: "Abstract Painting",
    category: "Art",
    price: 40,
    stock: 10,
    rating: 4.9,
    image: "/images/art1.png",
    description: "A bold abstract painting to brighten any room.",
    details: "This abstract painting features vibrant colors and dynamic shapes, perfect for adding a modern touch to any space.",
  },
  {
    name: "Village Sculpture",
    category: "Art",
    price: 45,
    stock: 10,
    rating: 4.8,
    image: "/images/art2.png",
    description: "Modern sculpture piece that adds character to any space",
    details: "This village sculpture is crafted with attention to detail, making it a unique addition to any art collection.",
  },
  {
    name: "Canvas painting",
    category: "Art",
    price: 50,
    stock: 10,
    rating: 4.7,
    image: "/images/art3.png",
    description: "High-quality canvas artwork with vibrant colors.",
    details: "This canvas painting is created with premium materials, ensuring long-lasting vibrancy and quality.",
  },
  {
    name: "Wall Art Piece",
    category: "Art",
    price: 38,
    stock: 10,
    rating: 4.6,
    image: "/images/art4.png",
    description: "Beautiful wall art designed to complement any decor.",
    details: "This wall art piece is crafted to enhance the aesthetic of any room, adding a touch of elegance and style.",
  },
  {
    name: "Wooden Bench",
    category: "Woodworking",
    price: 80,
    stock: 10,
    rating: 4.9,
    image: "/images/woodbench1.png",
    description: "Durable handcrafted wooden bench built to last.",
    details: "This wooden bench is designed for both comfort and durability, making it a perfect addition to any space.",
  },
  {
    name: "Wooden Table",
    category: "Woodworking",
    price: 120,
    stock: 10,
    rating: 4.8,
    image: "/images/woodentable1.png",
    description: "Elegant wooden table made with premium materials.",
    details: "This wooden table is crafted with care, offering both style and functionality for any dining or workspace.",
  },
  {
    name: "Key to the town rack",
    category: "Woodworking",
    price: 30,
    stock: 10,
    rating: 4.7,
    image: "/images/smallwoodcraft1.png",
    description: "Safe place to keep your keys.",
    details: "This key rack is designed to keep your keys organized and easily accessible, adding a touch of craftsmanship to your home.",
  },
  {
    name: "Acrylic Paint Set",
    category: "Paints",
    price: 20,
    stock: 10,
    rating: 4.8,
    image: "/images/paints1.png",
    description: "High-quality acrylic paint set for artists.",
    details: "This acrylic paint set includes a variety of colors, perfect for artists of all skill levels.",
  },
  {
    name: "Paint Brushes",
    category: "Paints",
    price: 15,
    stock: 10,
    rating: 4.7,
    image: "/images/paints2.png",
    description: "Durable paint brushes for smooth strokes.",
    details: "These paint brushes are designed for precision and durability, ensuring smooth and consistent strokes.",
  },
  {
    name: "Color Palette Kit",
    category: "Paints",
    price: 18,
    stock: 10,
    rating: 4.6,
    image: "/images/paints3.png",
    description: "Complete palette kit for mixing colors easily.",
    details: "This color palette kit provides a convenient way to mix and organize your paints, enhancing your creative process.",
  },
  {
    name: "Artist Supply Set",
    category: "Paints",
    price: 25,
    stock: 10,
    rating: 4.9,
    image: "/images/paints4.png",
    description: "All-in-one artist supply kit for beginners and pros.",
    details: "This artist supply set includes a variety of essential tools, making it perfect for both beginners and experienced artists.",
  },
  {
    name: "Hammer & Chisel Set",
    category: "Tools",
    price: 35,
    stock: 10,
    rating: 4.7,
    image: "/images/tools1.png",
    description: "Essential tools for woodworking and carving.",
    details: "This hammer and chisel set provides the necessary tools for precise woodworking and carving projects.",
  },
  {
    name: "Carving Tools",
    category: "Tools",
    price: 28,
    stock: 10,
    rating: 4.8,
    image: "/images/tools2.png",
    description: "Precision carving tools for detailed work.",
    details: "These carving tools are designed for intricate and detailed woodworking projects, ensuring accuracy and quality.",
  },
  {
    name: "Brush and sponge Tool Kit",
    category: "Tools",
    price: 22,
    stock: 10,
    rating: 4.6,
    image: "/images/tools3.png",
    description: "Multi-purpose brush and sponge kit for crafting.",
    details: "This brush and sponge tool kit is perfect for various crafting projects, providing versatility and ease of use.",
  },
  {
    name: "Craft Sponge Set",
    category: "Tools",
    price: 12,
    stock: 10,
    rating: 4.5,
    image: "/images/tools4.png",
    description: "Soft sponges ideal for painting and textures.",
    details: "These craft sponges are designed for creating various textures and effects in your artwork, enhancing your creative projects.",
  },
  {
    name: "Clay Vase",
    category: "Pottery",
    price: 26,
    stock: 10,
    rating: 4.9,
    image: "/images/pottery1.png",
    description: "Elegant clay vase handcrafted by artisans.",
    details: "This clay vase is meticulously handcrafted, showcasing the skill and artistry of its maker.",
  },
  {
    name: "Ceramic Jug",
    category: "Pottery",
    price: 30,
    stock: 10,
    rating: 4.8,
    image: "/images/pottery2.png",
    description: "Traditional ceramic jug with a modern twist.",
    details: "This ceramic jug combines traditional craftsmanship with a contemporary design, making it a versatile addition to any home.",
  },
  {
    name: "Decor Pitcher",
    category: "Pottery",
    price: 34,
    stock: 10,
    rating: 4.7,
    image: "/images/pottery3.png",
    description: "Decorative pitcher perfect for display.",
    details: "This decorative pitcher is designed to enhance any space, combining functionality with aesthetic appeal.",
  },
  {
    name: "Pottery jug",
    category: "Pottery",
    price: 20,
    stock: 10,
    rating: 4.6,
    image: "/images/pottery4.png",
    description: "Handmade pottery jug with unique patterns.",
    details: "This pottery jug is handcrafted with unique patterns, making each piece one-of-a-kind.",
  },
  {
    name: "Woven Basket",
    category: "Basketry",
    price: 22,
    stock: 10,
    rating: 4.8,
    image: "/images/basket1.png",
    description: "Durable woven basket for storage or decor.",
    details: "This woven basket is crafted for durability and style, perfect for storage or decorative purposes.",
  },
  {
    name: "Storage Basket",
    category: "Basketry",
    price: 24,
    stock: 10,
    rating: 4.7,
    image: "/images/basket2.png",
    description: "Stylish storage basket for organizing spaces.",
    details: "This storage basket combines style and functionality, ideal for keeping your spaces organized.",
  },
  {
    name: "Decor Basket",
    category: "Basketry",
    price: 20,
    stock: 10,
    rating: 4.6,
    image: "/images/basket3.png",
    description: "Decorative basket that blends style and function.",
    details: "This decorative basket is designed to enhance any space, combining aesthetic appeal with practical use.",
  },
  {
    name: "Gift Basket",
    category: "Basketry",
    price: 18,
    stock: 10,
    rating: 4.9,
    image: "/images/basket4.png",
    description: "Perfect basket for gifting and special occasions.",
    details: "This gift basket is thoughtfully curated, making it ideal for presenting gifts on special occasions.",
  },
  {
    name: "Wooden Chair",
    category: "Furniture",
    price: 70,
    stock: 10,
    rating: 4.8,
    image: "/images/furniture1.png",
    description: "Comfortable wooden chair with a classic design.",
    details: "This wooden chair combines comfort and classic design, making it a perfect addition to any room.",
  },
  {
    name: "Dining Table",
    category: "Furniture",
    price: 150,
    stock: 10,
    rating: 4.9,
    image: "/images/furniture2.png",
    description: "Spacious dining table for family gatherings.",
    details: "This dining table offers ample space for family gatherings, combining functionality with elegant design.",
  },
  {
    name: "Coffee Table",
    category: "Furniture",
    price: 90,
    stock: 10,
    rating: 4.7,
    image: "/images/furniture3.png",
    description: "Modern coffee table with sleek lines.",
    details: "This modern coffee table features sleek lines and a minimalist design, perfect for contemporary living spaces.",
  },
  {
    name: "Modern Coffee Table",
    category: "Furniture",
    price: 85,
    stock: 10,
    rating: 4.6,
    image: "/images/furniture4.png",
    description: "Stylish modern coffee Table.",
    details: "This stylish modern coffee table combines functionality with contemporary design, making it a versatile addition to any living room.",
  },
  {
    name: "White Modern furniture set",
    category: "Furniture",
    price: 60,
    stock: 10,
    rating: 4.8,
    image: "/images/furniture5.png",
    description: "White Modern furniture set.",
    details: "This white modern furniture set offers a clean and elegant look, perfect for contemporary interiors.",
  },
  {
    name: "Charcocal Love seat",
    category: "Furniture",
    price: 95,
    stock: 10,
    rating: 4.7,
    image: "/images/furniture6.png",
    description: "Bueatiful love seat.",
    details: "This charcoal love seat provides a cozy and stylish seating option, ideal for any living room.",
  },
  {
    name: "Twin chair set",
    category: "Furniture",
    price: 110,
    stock: 10,
    rating: 4.9,
    image: "/images/furniture7.png",
    description: "Modern and clean twin chairs.",
    details: "This twin chair set offers a modern and clean design, perfect for contemporary interiors.",
  },
  {
    name: "Matching chair set",
    category: "Furniture",
    price: 75,
    stock: 10,
    rating: 4.6,
    image: "/images/furniture8.png",
    description: "matching chair set.",
    details: "This matching chair set provides a cohesive and stylish seating arrangement, ideal for any living space.",
  },
  {
    name: "Gift Box Set",
    category: "Gifts",
    price: 20,
    stock: 10,
    rating: 4.9,
    image: "/images/gift1.png",
    description: "Curated gift box set for special occasions.",
    details: "This curated gift box set is perfect for celebrating special occasions, offering a thoughtful selection of items.",
  },
  {
    name: "Candle Gift Set",
    category: "Gifts",
    price: 22,
    stock: 10,
    rating: 4.8,
    image: "/images/gift2.png",
    description: "Scented candle set for relaxation.",
    details: "This scented candle set is designed to create a relaxing ambiance, perfect for unwinding after a long day.",
  },
  {
    name: "Ocean scented candle",
    category: "Gifts",
    price: 18,
    stock: 10,
    rating: 4.7,
    image: "/images/gift3.png",
    description: "Ocean scented candle.",
    details: "This ocean scented candle brings the refreshing scent of the sea into your home, creating a calming atmosphere.",
  },
  {
    name: "Cozy Candle",
    category: "Gifts",
    price: 16,
    stock: 10,
    rating: 4.9,
    image: "/images/gift4.png",
    description: "Cozy Candle.",
    details: "This cozy candle provides a warm and inviting ambiance, perfect for creating a relaxing atmosphere.",
  },
  {
    name: "Wood scented candle",
    category: "Gifts",
    price: 25,
    stock: 10,
    rating: 4.8,
    image: "/images/gift5.png",
    description: "Wood scented candle.",
    details: "This wood scented candle offers a rich and earthy aroma, creating a comforting and serene environment.",
  },
  {
    name: "Crotche toy goat",
    category: "Gifts",
    price: 28,
    stock: 10,
    rating: 4.7,
    image: "/images/gift6.png",
    description: "Crotche toy goat.",
    details: "This crocheted toy goat is a charming and playful addition to any gift collection, perfect for children and collectors alike.",
  },
];
